# Generated by Django 2.2.1 on 2019-07-26 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_auto_20190727_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 2, 15, 3, 155358), verbose_name='作成日時'),
        ),
    ]
