# Generated by Django 2.2.1 on 2019-07-26 20:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_photo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag_name',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='タグ名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='tag_ruby',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='タグ振り仮名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 5, 32, 14, 37604), verbose_name='作成日時'),
        ),
    ]
