# Generated by Django 2.2.1 on 2019-07-26 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0004_auto_20190727_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 5, 45, 0, 410895), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag_name',
            field=models.TextField(null=True, verbose_name='タグ名称'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag_ruby',
            field=models.TextField(null=True, verbose_name='タグ振り仮名'),
        ),
    ]
